[workspace]

members = [
    "rust-book/guessing-game",
    "rust-book/rectangle",
    "rust-book/temp-convert",
    "rust-book/fibonacci",
    "rust-book/twelve-days-of-christmas",
    "rust-by-example",
    "rustlings"
]